import Foundation

enum CategoryIconCatalog {
    static let icons: [String] = TallyIcon.Catalog.all

    static var sheetIcons: [String] {
        icons
    }

    static func accessibilityLabel(for iconKey: String) -> String {
        accessibilityLabels[iconKey] ?? iconKey
            .split(separator: "-")
            .map { $0.capitalized }
            .joined(separator: " ")
    }

    private static let accessibilityLabels: [String: String] = [
        TallyIcon.Catalog.forkKnife: "餐具",
        TallyIcon.Catalog.coffee: "咖啡",
        TallyIcon.Catalog.bowlFood: "餐碗",
        TallyIcon.Catalog.hamburger: "汉堡",
        TallyIcon.Catalog.pizza: "披萨",
        TallyIcon.Catalog.wine: "红酒",
        TallyIcon.Catalog.beerStein: "啤酒",
        TallyIcon.Catalog.iceCream: "冰淇淋",
        TallyIcon.Catalog.cookingPot: "烹饪",
        TallyIcon.Catalog.cake: "蛋糕",
        TallyIcon.Catalog.cookie: "饼干",
        TallyIcon.Catalog.shoppingCart: "购物车",
        TallyIcon.Catalog.shoppingBag: "购物袋",
        TallyIcon.Catalog.handbag: "手提包",
        TallyIcon.Catalog.tag: "标签",
        TallyIcon.Catalog.storefront: "商店",
        TallyIcon.Catalog.receipt: "小票",
        TallyIcon.Catalog.house: "房屋",
        TallyIcon.Catalog.couch: "沙发",
        TallyIcon.Catalog.bed: "床",
        TallyIcon.Catalog.lightbulb: "灯泡",
        TallyIcon.Catalog.lightning: "电费",
        TallyIcon.Catalog.drop: "水费",
        TallyIcon.Catalog.flame: "燃气",
        TallyIcon.Catalog.trash: "垃圾",
        TallyIcon.Catalog.wrench: "维修",
        TallyIcon.Catalog.car: "汽车",
        TallyIcon.Catalog.bus: "公交",
        TallyIcon.Catalog.train: "火车",
        TallyIcon.Catalog.airplaneTilt: "飞机",
        TallyIcon.Catalog.gasPump: "加油",
        TallyIcon.Catalog.bicycle: "自行车",
        TallyIcon.Catalog.motorcycle: "摩托车",
        TallyIcon.Catalog.taxi: "出租车",
        TallyIcon.Catalog.mapPin: "定位",
        TallyIcon.Catalog.firstAidKit: "急救箱",
        TallyIcon.Catalog.pill: "药片",
        TallyIcon.Catalog.heartbeat: "心跳",
        TallyIcon.Catalog.syringe: "注射",
        TallyIcon.Catalog.tooth: "牙齿",
        TallyIcon.Catalog.stethoscope: "听诊器",
        TallyIcon.Catalog.graduationCap: "毕业帽",
        TallyIcon.Catalog.bookOpen: "打开的书",
        TallyIcon.Catalog.books: "书籍",
        TallyIcon.Catalog.notebook: "笔记本",
        TallyIcon.Catalog.pencil: "铅笔",
        TallyIcon.Catalog.filmSlate: "电影",
        TallyIcon.Catalog.musicNotes: "音乐",
        TallyIcon.Catalog.gameController: "游戏手柄",
        TallyIcon.Catalog.popcorn: "爆米花",
        TallyIcon.Catalog.television: "电视",
        TallyIcon.Catalog.headphones: "耳机",
        TallyIcon.Catalog.ticket: "票券",
        TallyIcon.Catalog.camera: "相机",
        TallyIcon.Catalog.barbell: "杠铃",
        TallyIcon.Catalog.personSimpleRun: "跑步",
        TallyIcon.Catalog.soccerBall: "足球",
        TallyIcon.Catalog.basketball: "篮球",
        TallyIcon.Catalog.sneakerMove: "运动鞋",
        TallyIcon.Catalog.wifiHigh: "无线网络",
        TallyIcon.Catalog.phone: "电话",
        TallyIcon.Catalog.deviceMobile: "手机",
        TallyIcon.Catalog.laptop: "电脑",
        TallyIcon.Catalog.cloud: "云服务",
        TallyIcon.Catalog.tShirt: "T 恤",
        TallyIcon.Catalog.pants: "裤子",
        TallyIcon.Catalog.dress: "连衣裙",
        TallyIcon.Catalog.eyeglasses: "眼镜",
        TallyIcon.Catalog.scissors: "剪刀",
        TallyIcon.Catalog.pawPrint: "爪印",
        TallyIcon.Catalog.dog: "狗",
        TallyIcon.Catalog.cat: "猫",
        TallyIcon.Catalog.suitcaseRolling: "行李箱",
        TallyIcon.Catalog.mountains: "山",
        TallyIcon.Catalog.tent: "帐篷",
        TallyIcon.Catalog.globeHemisphereWest: "地球",
        TallyIcon.Catalog.heart: "爱心",
        TallyIcon.Catalog.handHeart: "爱心手掌",
        TallyIcon.Catalog.usersThree: "多人",
        TallyIcon.Catalog.baby: "婴儿",
        TallyIcon.Catalog.gift: "礼物",
        TallyIcon.Catalog.briefcase: "公文包",
        TallyIcon.Catalog.moneyWavy: "现金",
        TallyIcon.Catalog.bank: "银行",
        TallyIcon.Catalog.coins: "硬币",
        TallyIcon.Catalog.creditCard: "信用卡",
        TallyIcon.Catalog.wallet: "钱包",
        TallyIcon.Catalog.currencyCny: "人民币"
    ]
}
